services:
  web:
    build:
      context: .
      target: web
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    environment:
      PHP_OPCACHE_ENABLE: "0"
      NGINX_WEBROOT: /var/www/html/public

  cli:
    build:
      context: .
      target: cli
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: ["tail", "-f", "/dev/null"]
